"""
Django settings for gp2 project.
Generated by 'django-admin startproject' using Django 5.1.
For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from collections.abc import Callable
from typing import cast
from dataclasses import dataclass
import os
from ks_settings import env


def l(*args) -> list:
    return [a for a in args if a is not None]


def d(val: dict) -> dict:
    return {k: v for k, v in val.items() if v is not None}


def enable_when[T](flag: bool, val: T | Callable[[], T]) -> None | T:
    if flag:
        if callable(val):
            return cast(Callable[[], T], val)()
        else:
            return val


@dataclass(slots=True, kw_only=True)
class Settings:
    jinja2: bool
    django_rest_framework: bool
    browser_reload: bool
    disable_cache: bool
    minify_html: bool


SETTINGS: Settings


def settings(
    settings_locals: dict,
    *,
    apps: list[str],
    jinja2: bool = False,
    django_rest_framework: bool = False,
    browser_reload: bool = False,
    disable_cache: bool = True,
    minify_html: bool = False,
    pre_middleware: list[str] = [],
    middleware: list[str] = [],
    login_urls: list[str] = [],
    staticfiles_dirs: list[str] = ["public"],
):
    global SETTINGS
    SETTINGS = Settings(
        **{k: v for k, v in locals().items() if k in Settings.__slots__}
    )
    PROJECT_NAME = env.project_name()
    BASE_DIR = env.project_dir()
    DEBUG = os.environ.get("PRODUCTION", "") != "true"
    HOSTS = l(os.environ.get("HOST"))
    ALLOWED_HOSTS = l(enable_when(DEBUG, "*"), *HOSTS)
    CSRF_TRUSTED_ORIGINS = ["https://" + host for host in HOSTS]

    if not DEBUG and len(ALLOWED_HOSTS) == 0:
        raise Exception("Empty HOSTS env var in a production environment")

    MEDIA_URL = "media/"
    if DEBUG:
        MEDIA_ROOT = "media/"
    else:
        MEDIA_ROOT = f"/var/media/{PROJECT_NAME}"

    SECRET_KEY = "django-insecure-=f^dje6)gpg@y3!mt4dmji-r(@ghfz"
    if not DEBUG:
        SECRET_KEY = os.environ["SECRET_KEY"]

    INSTALLED_APPS = (
        l(
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            enable_when(browser_reload, "django_browser_reload"),
            # enable_when(jinja2, "jinja_utils"),
            enable_when(jinja2, "django_jinja"),
            enable_when(django_rest_framework, "rest_framework"),
        )
        + apps
    )

    MIDDLEWARE = (
        pre_middleware
        + l(
            enable_when(disable_cache, "ks_settings.middleware.DisableCacheMiddleware"),
            "django.middleware.security.SecurityMiddleware",
            "django.middleware.locale.LocaleMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            enable_when(
                minify_html, "django_minify_html.middleware.MinifyHtmlMiddleware"
            ),
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            enable_when(
                len(login_urls) > 0, "ks_settings.middleware.LoginRequiredMiddleware"
            ),
        )
        + middleware
    )
    ROOT_URLCONF = f"{PROJECT_NAME}.urls"
    TEMPLATES = l(
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
        enable_when(
            jinja2,
            {
                "BACKEND": "django_jinja.jinja2.Jinja2",
                "NAME": "jinja2",
                "DIRS": ["templates"],
                "OPTIONS": {
                    "match_extension": ".j2",
                    "globals": d(
                        {
                            "django_browser_reload_script": enable_when(
                                browser_reload,
                                "django_browser_reload.jinja.django_browser_reload_script",
                            ),
                            "debug": DEBUG,
                            "testing": not DEBUG,
                            "development": DEBUG,
                        }
                    ),
                },
            },
        ),
    )
    WSGI_APPLICATION = f"{PROJECT_NAME}.wsgi.application"

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    LANGUAGE_CODE = "pt-br"
    TIME_ZONE = "America/Sao_Paulo"
    USE_I18N = True
    USE_L10N = True
    USE_TZ = True

    STATIC_URL = "static/"
    STATICFILES_DIRS = [BASE_DIR / dir for dir in staticfiles_dirs]
    if not DEBUG:
        STATIC_ROOT = f"/var/static/{PROJECT_NAME}"

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
    settings_locals.update(locals())
